import Add from '@material-ui/icons/Add';
import FilterList from '@material-ui/icons/FilterList';
import Sort from '@material-ui/icons/Sort';
import ArrowDownward from '@material-ui/icons/ArrowDownward';
import ArrowUpward from '@material-ui/icons/ArrowUpward';
import ArrowLeft from '@material-ui/icons/ArrowLeft';
import ArrowRight from '@material-ui/icons/ArrowRight';
import ViewColumn from '@material-ui/icons/ViewColumn';
import LineWeight from '@material-ui/icons/LineWeight';
import SaveAltIcon from '@material-ui/icons/SaveAlt';

export const AddIcon = Add;
export const ArrowLeftIcon = ArrowLeft;
export const ArrowRightIcon = ArrowRight;
export const FilterIcon = FilterList;
export const ColumnsIcon = ViewColumn;
export const DensityIcon = LineWeight;
export const ExportIcon = SaveAltIcon;
export const SortAscIcon = ArrowUpward;
export const SortDescIcon = ArrowDownward;
export const SortIcon = Sort;
